added rerun cohort support to interactive script , including reimport of keyfile

diff --git a/_run_gbs_qc b/_run_gbs_qc
--- a/_run_gbs_qc
+++ b/_run_gbs_qc
@@ -432,6 +432,72 @@ function get_cohort_opts() {
    read_answer_with_default $LIBRARY_MONIKERS
    LIBRARY_MONIKERS=$answer
 
+   # check if already run - if so prompt for reimport
+   to_do=""
+   to_import=""
+   for library_moniker in $LIBRARY_MONIKERS; do
+      # look for landmark file(s)  
+      ls $OUTPUT_ROOT/*.${library_moniker}*.demultiplex > $OUTPUT_ROOT/manifest.txt 2>&1
+      grep -q "cannot access" $OUTPUT_ROOT/manifest.txt 
+      if [ $? != 0 ]; then
+          echo "looks like $library_moniker has already been processed (found landmarks )"
+          echo "do you want to reprocess this library ? (y/n, default = y)"
+          read_answer_with_default y
+          if [ $answer != "y" ]; then
+             echo "ok skipping $library_moniker"
+             continue
+          else
+             to_do="$to_do $library_moniker"
+             echo "ok will reprocess $library_moniker "
+             echo "do you need the keyfile re-imported ? (y/n, default =y)"
+             read_answer_with_default y
+             if [ $answer != "y" ]; then
+                 echo "ok will not reimport keyfile"
+             else
+                 to_import="$to_import $library_moniker"
+                 echo "ok will reimport keyfile"
+             fi
+          fi
+      else
+          to_do="$to_do $library_moniker"
+      fi
+   done
+
+   # exit if nothing to do ; run imports if any to do
+   LIBRARY_MONIKERS=$to_do
+   if [ -z "$LIBRARY_MONIKERS" ]; then
+      echo "quitting , nothing to do"
+      exit 1
+   fi
+
+   if [ ! -z "$to_import" ]; then
+      echo "about to reimport keyfiles for $to_import - ok ? (y/n, default = y)"
+      read_answer_with_default y
+      if [ $answer != "y" ]; then
+         echo "ok quitting"
+         exit 1
+      fi
+      for library in $to_import; do
+         echo "running $GBS_PRISM_BIN/database_prism.sh -i -t reimport_library -r $RUN -s $library "
+         echo "press Enter to continue. . ."
+         read answer
+         $GBS_PRISM_BIN/database_prism.sh -i -t reimport_library -r $RUN -s $library
+         return_code=$?
+         if [ $return_code != 0 ]; then
+            echo "looks like there was a problem with the import (exit code $return_code)  - check $OUTPUT_ROOT/reimport.log - quitting"
+            exit 1
+         fi
+      done
+
+      echo "*** finished reimporting keyfiles  ***"
+
+      echo "updating processing parameters"
+      mv $OUTPUT_ROOT/SampleProcessing.json $OUTPUT_ROOT/SampleProcessing.json.old
+      get_processing_parameters
+
+   fi
+
+
    echo "getting default GBS cohorts to process. . .
 
    "
@@ -446,6 +512,22 @@ function get_cohort_opts() {
    echo "please enter gbs cohorts to process (default=$gbs_cohorts)"
    read_answer_with_default $gbs_cohorts
    GBS_COHORTS=$answer
+
+
+   # optionally clean up 
+   for cohort in $GBS_COHORTS; do
+      if [ -d $OUTPUT_ROOT/$cohort ]; then
+         echo "found existing results for $cohort in $OUTPUT_ROOT/$cohort - do you want to reset this cohort ? (y/n, default = y)"
+         read_answer_with_default y
+         if [ $answer != "y" ]; then
+            echo "ok not cleaning - note , rerun may be incomplete"
+         else
+            set -x
+            $GBS_PRISM_BIN/ag_gbs_qc_prism.sh -f -C local -a clean -O $OUTPUT_ROOT -r $RUN $cohort  
+            set +x
+         fi
+      fi
+   done
 }
 
 
